import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import Script from "next/script";
import { Toaster } from "sonner";
import { cn } from "@/lib/utils";
import "./globals.css";

const jetbrainsMono = JetBrains_Mono({
	subsets: ["latin"],
	variable: "--font-mono",
});

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Tech Radar",
	description: "Generated by create next app",
};

const themeInitScript = `
try {
	if (localStorage.getItem("theme") === "dark") {
		document.documentElement.classList.add("dark");
	}
} catch (_) {}
`;

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		// TODO: fix theming flash on page load
		<html
			lang="en"
			className={cn("font-mono", jetbrainsMono.variable)}
			suppressHydrationWarning
		>
			<head>
				<Script id="theme-init" strategy="beforeInteractive">
					{themeInitScript}
				</Script>
			</head>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				{children}
				<Toaster position="top-right" />
			</body>
		</html>
	);
}
