---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets
  namespace: techradar
spec:
  encryptedData:
    JWT_SECRET: AgAZ/k3Em/CZnc38psbCuREvBnCPmFe21xnsCsDAmoo4CvjawUaKpIL5sVAyPlA7W0yD5hG3pInwQ6fjjMO3r30Ci67fYGfPRRK5DolfDBA9Qlzjs1lsAlVNgOOaxZpGqBbFg/KpViuAgxY1F6CG4omvyABD+7GA5uQVkcwwPwQplyc4Hp2WQTZluVSK17cieyLvLpAzHWQldG11qf38gMRyBIVqxvSoRj/MbwwpMukM4nMkklxqRlAoKOshwc3AYxBIRuiKmfxPQ55xj/Z/7JD5433zOOzAdJd6YHx+ZGZCRLoZKAEst7toeue4wB9PIet3exbAKpWLzpSQWfoB3ewB7NOBr+/CToFnAtxE3U25I5s93L5zqvsUvOZlBKFXjr6E5CX/GUVmeBCl+du4yMYOx+VHBaADlxrCvMd8re3ANsaMYgfnTxxrRRgUQYPQRCwSUQCvGLSlrFbsB8jjvKC5z/SqWDkxQbF5g50gYNYydiX+Gnah3dvK+H6d/kV0cnWP10+CYawxOeOjLqR+4UqFTuU3PW5qK59mmUxtIRsUdSqZfFQB4eaxIdI/G15eUuDFi7XN0aY4YVuJFcDt45rxt5cyjZKCpIMF2rQrlj9SE2hifyKT9ipphnC67cpa0ojg1yb8POLRmPyfQXQKlRCHyncSr1Fb/7HpyxuP1beXCQxKX1aCbLrCUgQxhkohcK6l5szWWFV5IHpi6Qav7UO1G0gFVgueSCrJCBxt9S4AuLXL+UqimvSbYWYsMg==
  template:
    metadata:
      name: backend-secrets
      namespace: techradar
